// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7UZawhHwolXwDLtWCQXWgsdFDRosITc8',
    appId: '1:1064604167062:web:2eb07f9201c872a4438bb7',
    messagingSenderId: '1064604167062',
    projectId: 'advmobprog-firebase-2adff',
    authDomain: 'advmobprog-firebase-2adff.firebaseapp.com',
    storageBucket: 'advmobprog-firebase-2adff.firebasestorage.app',
    measurementId: 'G-EVK7EEWCGZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtk4xJtGoWbBIcc1BnUNwyQqyBiJOme9k',
    appId: '1:1064604167062:android:282c08bd508e1197438bb7',
    messagingSenderId: '1064604167062',
    projectId: 'advmobprog-firebase-2adff',
    storageBucket: 'advmobprog-firebase-2adff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIl5VcOWQWWiptaw15ev77TWCRu3OL4FY',
    appId: '1:1064604167062:ios:703482175cb4f0a6438bb7',
    messagingSenderId: '1064604167062',
    projectId: 'advmobprog-firebase-2adff',
    storageBucket: 'advmobprog-firebase-2adff.firebasestorage.app',
    iosBundleId: 'com.example.bisocosAdvmobprog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7UZawhHwolXwDLtWCQXWgsdFDRosITc8',
    appId: '1:1064604167062:web:4b3ae5b79f0ebcce438bb7',
    messagingSenderId: '1064604167062',
    projectId: 'advmobprog-firebase-2adff',
    authDomain: 'advmobprog-firebase-2adff.firebaseapp.com',
    storageBucket: 'advmobprog-firebase-2adff.firebasestorage.app',
    measurementId: 'G-B2B4N0RZQR',
  );
}
